

const Skills = () => {
    return (
        <div>
            <h2>Skills</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa magni corrupti corporis in rem excepturi deserunt deleniti! Voluptate facilis alias, quis voluptatum et deserunt dolore neque magnam numquam eos impedit ab accusamus nostrum error voluptatem obcaecati aperiam omnis molestias? Non enim fuga repudiandae at ipsum repellat repellendus omnis pariatur praesentium reprehenderit eius veniam, nihil similique provident! Commodi vero optio labore provident impedit eveniet nesciunt earum, porro minima ipsum et ratione, saepe adipisci animi doloremque voluptate in ex delectus illum, ea nihil! Voluptatibus ab unde eius fugit aspernatur tempore. Sint vitae ducimus sit ipsam tenetur eos, praesentium reiciendis. Eaque eos fugit commodi. Aliquid, illum? Qui, aliquid! Debitis voluptatem, sequi et ipsum reiciendis quibusdam quae, nemo facere libero iure repudiandae adipisci impedit? Dolores quos vitae iusto ipsa impedit corrupti itaque tempora accusamus et culpa minus, similique doloremque totam dolorum animi ipsam deleniti? Obcaecati provident animi, aliquam accusamus sed cum culpa ullam est, ad inventore, accusantium natus vel pariatur dolor debitis facilis reprehenderit minima. Dignissimos delectus consectetur laudantium sunt consequuntur saepe mollitia molestiae distinctio fugiat! Officia doloremque beatae rerum labore ab et ratione a consectetur fugit nesciunt soluta reprehenderit rem asperiores nulla placeat atque eos veritatis, in repellat deserunt excepturi repudiandae dolor dolorum dignissimos. Natus, fugit. Quas pariatur, ea in quidem eius cum consequuntur deserunt sapiente quia repudiandae doloribus. Aut quas tenetur, earum, provident laudantium est recusandae similique officia alias, ducimus unde enim nostrum nesciunt maiores at? Impedit, ratione quidem est nemo minus vero corrupti eaque fugit officiis consequuntur laborum asperiores voluptatum unde assumenda natus alias a quas, animi doloribus quos quis distinctio! Repellat, placeat ipsa aliquam quos blanditiis iste beatae impedit! Illum nisi, repellendus qui itaque beatae sapiente neque aliquid asperiores, veniam dicta quia? Dolor ea, autem, dolore pariatur odit, modi architecto quod fugit provident voluptatibus esse dignissimos unde a quia facere?</p>
        </div>
    );
};

export default Skills;